import "../globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import MobileMenu from "@/components/mobile-menu";
import TopNavigation from "@/components/top-navigation";
import { Providers } from "../../app/providers";




const poppins = Poppins({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Studio Hofmann",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>

        <TopNavigation />
        <Providers>
          {children}
        </Providers>
        <MobileMenu />

      </body>

    </html>
  );
}
